String GENERALTERMS = "By accessing and placing an order with DynamicTech IT Solution LLC,"
    " you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below."
    " These terms apply to the entire website and any email or other type of communication between you and DynamicTech IT Solution LLC."
    "Under no circumstances shall DynamicTech IT Solution LLC team be liable for any direct, indirect, "
    "special, incidental, or consequential damages, including, but not limited to, "
    "loss of data or profit, arising out of the use, or the inability to use, the materials on this "
    "site, even if DynamicTech IT Solution LLC team or an authorized representative has been advised "
    "of the possibility of such damages. If your use of materials from this site results "
    "in the need for servicing, repair, or correction of equipment or data,"
    " you assume any costs thereof."
    "DynamicTech IT Solution LLC will not be responsible for any outcome that may occur during the course of "
    "usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment.";
String LICENSE = "DynamicTech IT Solution LLC grants you a revocable, non-exclusive, "
    "non-transferable, limited license to download, "
    "install and use the website/app strictly in accordance with the terms of this Agreement.These Terms & Conditions are a"
    " contract between you and DynamicTech IT Solution LLC (referred to in these Terms & Conditions as "
    "“DynamicTech IT Solution LLC”, “us”, “we” or “our”), the provider of the DynamicTech IT Solution LLC "
    "website and the services accessible from the DynamicTech IT Solution LLC website "
    "(which are collectively referred to in these Terms & Conditions as the “DynamicTech IT Solution LLC Service”)."
    "You are agreeing to be bound by these Terms & Conditions. "
    "If you do not agree to these Terms & Conditions, please do not use the DynamicTech IT Solution LLC "
    "Service. In these Terms & Conditions, “you” refers both to you as an individual and to the entity you represent. "
    "If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to"
    " your account without notice.";

String DEFINITIONS_AND_KEY_TERMS =
    "To help explain things as clearly as possible in this Terms & Conditions, "
    "every time any of these terms are referenced, are strictly defined as:Cookie: small amount of "
    "data generated by a website and saved by your web browser. It is used to identify your browser, "
    "provide analytics, remember information about you such as your language preference or login "
    "information.Company: when these terms mention “Company,” “we,” “us,” or “our,” it refers to "
    "DynamicTech IT Solution LLC, which is responsible for your information under these Terms & "
    "Conditions.Country: where DynamicTech IT Solution LLC or the owners/founders of DynamicTech "
    "IT Solution LLC are based, in this case, is the United Arab EmiratesDevice: any internet-connected "
    "device such as a phone, tablet, computer, or any other device that can be used to visit DynamicTech "
    "IT Solution LLC and use the services.Service: refers to the service provided by DynamicTech IT "
    "Solution LLC as described in the relative terms (if available) and on this platform."
    "Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners,"
    " and others who provide our content or whose products or services we think may interest you.Website: "
    "DynamicTech IT Solution LLC’s site, which can be accessed via this URL: https://dynamictech.aeYou: "
    "a person or entity that is registered with DynamicTech IT Solution LLC to use the Services.";

String RESTRICTIONS = "You agree not to, and you will not permit others to:License, sell,"
    " rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise"
    " commercially exploit the website/app or make the platform available to any third party."
    "Modify, make derivative works of, disassemble, decrypt, reverse compile or r"
    "everse engineer any part of the website/app.Remove, alter or obscure any proprietary not"
    "ice (including any notice of copyright or trademark) of DynamicTech IT Solution LLC or "
    "its affiliates, partners, suppliers, or the licensors of the website/app.";

String PAYMENT =
    "If you register to any of our recurring payment plans, you agree to pay all fees or charges to your "
    "account for the Service in accordance with the fees, charges, and billing terms in effect at the time that each "
    "fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide DynamicTech IT "
    "Solution LLC with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) (“Payment Provider”) "
    "as a condition to signing up for the Premium plan. Your Payment Provider agreement governs your use of the designated"
    " credit card account, and you must refer to that agreement and not these Terms to determine your rights and "
    "liabilities with respect to your Payment Provider. By providing DynamicTech IT Solution LLC with your credit "
    "card number and associated payment information, you agree that DynamicTech IT Solution LLC is authorized to "
    "verify information immediately, and subsequently invoice your account for all fees and charges due and payable"
    " to DynamicTech IT Solution LLC hereunder and that no additional notice or consent is required. You agree to "
    "immediately notify DynamicTech IT Solution LLC of any change in your billing address or the credit card used "
    "for payment hereunder. DynamicTech IT Solution LLC reserves the right at any time to change its prices and "
    "billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization’s"
    " administrator(s).Any attorney fees, court costs, or other costs incurred in the collection of delinquent"
    " undisputed amounts shall be the responsibility of and paid for by you.No contract will exist between "
    "you and DynamicTech IT Solution LLC for the Service until DynamicTech IT Solution LLC accepts your "
    "order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.You are "
    "responsible "
    "for any third-party fees that you may incur when using the Service.";
String YOUR_SUGGESTIONS =
    "Any feedback, comments, ideas, improvements or suggestions (collectively, “Suggestions”) provided by you to DynamicTech IT Solution LLC with respect to the website/app shall remain the sole and exclusive property of DynamicTech IT Solution LLC.DynamicTech IT Solution LLC shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.";
String YOUR_CONSENT =
    "We’ve updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.";
